// <auto-generated />
using ApiTiemposDeAlimentacion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiTiemposDeAlimentacion.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201028060052_MigrationInicial")]
    partial class MigrationInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiTiemposDeAlimentacion.Models.ClsModuloHabitacional", b =>
                {
                    b.Property<string>("ModuloHabitacional")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModuloHabitacional");

                    b.ToTable("ClsModuloHabitacional");
                });
#pragma warning restore 612, 618
        }
    }
}
